#:import utils kivy.utils
#:import * kivy.graphics
#:include SplashScreen splashscreen.SplashScreen

<SplashScreen>:
    on_enter:
        app.animate_splash(splash)
    BoxLayout:
        id: splash
        orientation: 'vertical'
        canvas:
            Color:
                rgba: (1, 1, 1, 1) #image opacity
            Rectangle:
                size: self.size
                source: 'assets/img/splash.jpg'